name: 'Helm Package & Push'
description: 'Packages a Helm chart and pushes it to a ChartMuseum repository'

inputs:
  helm-path:
    description: 'The path to the Helm chart directory'
    required: false
    default: 'helm'
  chart-version:
    description: 'The version of the Helm chart to package'
    required: true
  chartmuseum-url:
    description: 'The URL of the ChartMuseum repository'
    required: true

runs:
  using: composite

  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Install helm-push plugin
      shell: bash
      run: helm plugin install https://github.com/chartmuseum/helm-push

    - name: Add ChartMuseum repo
      shell: bash
      run: helm repo add chartmuseum ${{ inputs.chartmuseum-url }}

    - name: Package Helm chart
      shell: bash
      run: |
        helm dependency update ${{ inputs.helm-path }}
        helm package helm --version ${{ inputs.chart-version }} --app-version ${{ inputs.chart-version }}

    - name: Push chart to ChartMuseum
      shell: bash
      run: |
        CHART_PACKAGE=$(ls *.tgz)
        helm cm-push "$CHART_PACKAGE" chartmuseum
