name: "Docker Build & Push to ECR"
description: "Builds a Docker image and pushes it to Amazon ECR"

inputs:
  image-repo-name:
    description: "The name of the ECR repository to push the Docker image to"
    required: true
  image-tag:
    description: "The tag for the Docker image"
    required: true
  aws-access-key:
    description: "AWS Access Key ID"
    required: true
  aws-secret-key:
    description: "AWS Secret Access Key"
    required: true

runs:
  using: composite

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build image tag
      shell: bash
      id: vars
      run: |
        ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
        IMAGE_REPO_NAME=${{ inputs.image-repo-name }}
        REVISION=${{ inputs.image-tag }}
        IMAGE_TAG=${REVISION:-latest}
        IMAGE_URI=$ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
        
        echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

    - name: Build Docker image
      shell: bash
      run: |
        docker build -t ${{ steps.vars.outputs.image_uri }} .

    - name: Push Docker image
      shell: bash
      run: |
        docker push ${{ steps.vars.outputs.image_uri }}