name: Publish Tests Reports to PR

description: Action to publish Maven Failsafe and Surefire Tests Reports as comment to a PR.

inputs:
  initial-comment-message:
    description: Initial text for the comment posted on the PR
    required: false
    default: |
      ## Test Reports for run [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
      Reports will be posted here as they get available.

  comment-message:
    description: |
      Message appended to the comment posted on the PR. The message can be templated for replacement:
      - {0} is inputs'.'unit-test-title or integration-tests-title
      - {1} is the number of successful tests
      - {2} is the number of failed tests
      - {3} is the number of skipped tests
      - {4} is the URL to the HTML-Report
    required: false
    default: |
      ## {0}
      | Passed | Failed | Skipped | Report
      |--------|--------|---------|---------|
      | ✅ {1} | ❌ {2} | ⚠️ {3}   | See it [here]({4})

  unit-tests-title:
    description: The title of unit tests report
    required: false
    default: Unit tests report

  integration-tests-title:
    description: The title of integration tests report
    required: false
    default: Integration tests report

runs:
  using: composite

  steps:
    - name: Check pull request event
      uses: actions/github-script@v7
      if: ${{ github.event_name != 'pull_request' }}
      with:
        script: core.setFailed('This composite action should be only used on pull_request event')

    - name: (Re)create Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: reports
        hide_and_recreate: true
        hide_classify: 'OUTDATED'
        message: ${{ inputs.initial-comment-message }}

    - name: Generate Unit Tests Report
      id: generate-report-unit
      uses: phoenix-actions/test-reporting@v15
      if: ${{ hashFiles('**/target/surefire-reports/TEST-*.xml') != '' }}
      with:
        fail-on-error: false
        list-suites: all
        list-tests: all
        name: ${{ inputs.unit-tests-title }}
        only-summary: false
        path: '**/target/surefire-reports/TEST-*.xml'
        reporter: java-junit

    - name: Update PR status comment (unit tests)
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ steps.generate-report-unit.conclusion == 'success' }}
      with:
        append: true
        header: reports
        message: ${{ format(inputs.comment-message , inputs.unit-tests-title, steps.generate-report-unit.outputs.passed, steps.generate-report-unit.outputs.failed, steps.generate-report-unit.outputs.skipped, steps.generate-report-unit.outputs.runHtmlUrl) }}

    - name: Generate Integration Tests Report
      id: generate-report-integration
      uses: phoenix-actions/test-reporting@v15
      if: ${{ hashFiles('**/target/failsafe-reports/TEST-*.xml') != '' }}
      with:
        fail-on-error: false
        list-suites: all
        list-tests: all
        name: ${{ inputs.integration-tests-title }}
        only-summary: false
        path: '**/target/failsafe-reports/TEST-*.xml'
        reporter: java-junit

    - name: Update PR status comment (integration tests)
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ steps.generate-report-integration.conclusion == 'success' }}
      with:
        append: true
        header: reports
        message: ${{ format(inputs.comment-message , inputs.integration-tests-title, steps.generate-report-integration.outputs.passed, steps.generate-report-integration.outputs.failed, steps.generate-report-integration.outputs.skipped, steps.generate-report-integration.outputs.runHtmlUrl) }}